### ISSUE TITLE
Package cnest and submit to Pypi

### ISSUE THREAD

**Issue by breakds** [HorizonRobotics/alf#970]
# Motivation

This is to make cnest first-class citizen, the same as other dependencies of alf. With this, we hope the user of alf do not have to treat cnest with special care.

# Tasks

- [x] Documentation
- [x] Poetry Package
- [x] Submit to Pypi
- [x] Update alf to use the Pypi version
- [x] Test and verify

**Comment by breakds** [comment]
1. The repo is created at https://github.com/HorizonRobotics/cnest
2. Also migrated the tests and made sure that all tests passed
3. Submitted the package to pypi at https://pypi.org/project/cnest/
